#config_version=6

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

mode_settings:
  selectable_items:
    - title
    - credits
    - mpf_logo
  next_item_events: s_right_flipper_active
  previous_item_events: s_left_flipper_active

slide_player:
  mode_attract_started: attract

sound_player:
  mode_attract_started:
    mf_barnum_and_bailey_rag:
      bus: music
      