#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

hardware:
    platform: fast

fast:
  net:
    controller: neuron
    io_loop:
      cab:
        model: FP-I/O-0024
        order: 1

      3208:
        model: FP-I/O-3208
        order: 2

      1616:
        model: FP-I/O-1616
        order: 3

      "0804":
        model: FP-I/O-0804
        order: 4
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms

  
autofire_coils:
    left_sling:
        coil: c_left_sling
        switch: s_left_sling
    right_sling:
        coil: c_right_sling
        switch: s_right_sling
    left_rear_pop:
        coil: c_left_rear_pop
        switch: s_left_rear_pop
    right_rear_pop:
        coil: c_right_rear_pop
        switch: s_right_rear_pop
    left_front_pop:
        coil: c_left_front_pop
        switch: s_left_front_pop
    right_front_pop:
        coil: c_right_front_pop
        switch: s_right_front_pop


    

playfields:
    playfield:
        default_source_device: bd_trough
        tags: default

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        eos_switch: s_left_eos
        use_eos: true
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        eos_switch: s_right_eos
        use_eos: true
        enable_events: machine_reset_phase_3
    left_upper_level_flipper:
        main_coil: c_flipper_left_upper_level_main
        hold_coil: c_flipper_left_upper_level_hold
        activation_switch: s_left_flipper
        eos_switch: s_left_upper_level_flipper_eos
        use_eos: true
        enable_events: s_left_ramp_exit_active, s_right_ramp_exit_active
        disable_events: s_wireform_exit_left_opto_active, s_wireform_exit_right_opto_active, ball_will_end
    right_upper_level_flipper:
        main_coil: c_flipper_right_upper_level_main
        hold_coil: c_flipper_right_upper_level_hold
        activation_switch: s_right_flipper
        eos_switch: s_right_upper_level_flipper_eos
        use_eos: true
        enable_events: s_right_ramp_exit_active, s_left_ramp_exit_active
        disable_events: s_wireform_exit_left_opto_active, s_wireform_exit_right_opto_active, ball_will_end



config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml

    

modes:
  - attract
  - base