#config_version=6

mode:
  start_events: start_mode_pops
  stop_events: stop_mode_pops
  priority: 200

shots:
  pop_left_front:
    switch: s_left_front_pop
  pop_right_front:
    switch: s_right_front_pop
  pop_left_rear:
    switch: s_left_rear_pop
  pop_right_rear:
    switch: s_right_rear_pop
  
shot_groups:
  pops:
    shots: pop_left_front, pop_right_front, pop_left_rear, pop_right_rear

variable_player:
  pops_hit: 
    score: 100